# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sourcesync Pro
email: fioan89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A fast, one-way file synchronization tool for IntelliJ based products.
twitter_username: fioan89
github_username:  fioan89
blank_title: true
favicon: true
show_downloads: false

domain: fioan89.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://fioan89.github.io/sourcesync-pro  # the base hostname and protocol for your site, e.g. http://example.com

# Build settings
remote_theme: BDHU/minimalist
color-scheme: auto
svg:
  optimize: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-inline-svg

sidebar:
  - name: Home
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.3em;" width="1.5em" height="1.5em" preserveAspectRatio="xMidYMid meet" viewBox="0 -960 960 960"><path d="M240-200h147.692v-235.385h184.616V-200H720v-360L480-741.538 240-560v360Zm-40 40v-420l280-211.539L760-580v420H532.308v-235.384H427.692V-160H200Zm280-310.769Z" fill="currentColor"/></svg>
    link: /sourcesyncpro
  - name: User Guide
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.3em;" width="1.5em" height="1.5em" preserveAspectRatio="xMidYMid meet"><path d="M215.384-160q-23.057 0-39.221-16.163Q160-192.327 160-215.384v-529.232q0-23.057 16.163-39.221Q192.327-800 215.384-800h529.232q23.057 0 39.221 16.163Q800-767.673 800-744.616v529.232q0 23.057-16.163 39.221Q767.673-160 744.616-160H215.384Zm-24.615-584.616v529.232q0 9.23 7.692 16.923 7.693 7.692 16.923 7.692h529.232q9.23 0 16.923-7.692 7.692-7.693 7.692-16.923v-529.232q0-9.23-7.692-16.923-7.693-7.692-16.923-7.692h-86.308v244.385l-79.539-47.462L500-524.846v-244.385H215.384q-9.23 0-16.923 7.692-7.692 7.693-7.692 16.923Zm0 553.847v-578.462 578.462Z" fill="currentColor"/></svg>
    link: /sourcesyncpro/userguide
  - name: EULA
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.3em;" width="1.5em" height="1.5em" preserveAspectRatio="xMidYMid meet" viewBox="0 -960 960 960"><path d="M400-340h160q8.5 0 14.25-5.75T580-360v-60h-40v40H420v-200h120v40h40v-60.027q0-8.512-5.75-14.242Q568.5-620 560-620H400q-8.5 0-14.25 5.75T380-600v240q0 8.5 5.75 14.25T400-340Zm80.134 220q-74.673 0-140.41-28.339-65.737-28.34-114.365-76.922-48.627-48.582-76.993-114.257Q120-405.194 120-479.866q0-74.673 28.339-140.41 28.34-65.737 76.922-114.365 48.582-48.627 114.257-76.993Q405.194-840 479.866-840q74.673 0 140.41 28.339 65.737 28.34 114.365 76.922 48.627 48.582 76.993 114.257Q840-554.806 840-480.134q0 74.673-28.339 140.41-28.34 65.737-76.922 114.365-48.582 48.627-114.257 76.993Q554.806-120 480.134-120ZM480-160q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z" fill="currentColor"/></svg>
    link: /sourcesyncpro/licensing

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
